### ISSUE TITLE
Payment channel transactions should be saved if not found

### ISSUE THREAD

**Issue by rllola** [ShibeTechnology/dogecoin-spv-node#4]
When we resync the SPV and we encounter an open channel, we verify if the transaction is saved in the `redeemScript` database. If the database is empty it will throw an error. We should be able to correctly figure out what to do without throwing errors.

**Comment by rllola** [comment]
The error
```
/home/lola/Workspace/Dogecoin/dogecoin-spv-node/node_modules/levelup/lib/levelup.js:188
        err = new NotFoundError('Key not found in database [' + key + ']', err)
              ^
Error [NotFoundError]: Key not found in database [c06d1bf2f34fc83a8071893fd99778277e33ea30]
    at /home/lola/Workspace/Dogecoin/dogecoin-spv-node/node_modules/levelup/lib/levelup.js:188:15
    at /home/lola/Workspace/Dogecoin/dogecoin-spv-node/node_modules/encoding-down/index.js:75:21 {
  [cause]: [Error: NotFound: ]
}
```
